version: '3'

services:
  sirius:
    build:
      context: .
      dockerfile: sirius.dockerfile
    restart: always
    ports:
      - "80:80"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./internal/task_state/task_state_logs:/internal/task_state/task_state_logs
      - ./internal/task_result/result-logs:/internal/task_result/result-logs